### PR TITLE
Add OSX shortcut to quit the python interpreter.

### PR DESCRIPTION
**Pull request by jonathangeovani**
Missing shortcut to quit terminal on OSX. This PR is to add the shortcut to improve the experience for Mac users.

### CODE REVIEW

**Comment by lordloki** [comment]
Thanks for the PR. I will test the solution in the weekend and come back to apply it

**Comment by lordloki** [comment]
Hi, I just test and in my macos system "exit" doesn't work. Only works using exit() or CTRL+D. Could you test in yours?

**Comment by jonathangeovani** [comment]
I apologize for the mistake. in fact, the shortcut to exit the Python interpreter on Mac OS is CTRL+D.

**Comment by lordloki** [comment]
No problem. 
If you remove last "else" condition and transform the "elseif linux" condition in an "else" to cover linux and mac, I could apply your pull.

**Comment by jonathangeovani** [comment]
It's done. Thanks.

**Comment by youle31** [comment]
Thanks very much to you both, I merge this one too, as it seems ok now. Thanks!

**Pull request merged**
