### PR TITLE
UPBGE: Armature animation performances with big vbos on windows

### PR DESCRIPTION
**Pull request by youle31**
DO NOT REVIEW

It's just an experiment that I wanted to share related to a bottleneck happening for animation playing in some cases on windows.

The code here shows a way to have a little speed gain in 1 scene at least with armatures with big vertex buffer objects.

Principles:

- Change the way the vbos are updated from glBufferSubData to glMapBuffer
- Change the way the vbos are created from usage GPU_USAGE_STATIC to GPU_USAGE_STREAM or GPU_USAGE_DYNAMIC

Notes:

- The principles work only when combined (GPU_USAGE_STREAM + glMapBuffer) and DURING animation playing
- The performance gain is mainly noticeable on windows OS with my hardware at least (8700k, RTX 3070)
- I applied this only to vbo.pos_nor and vbo.lnor because i noticed they had a big performance cost
- Once animation finished to play, it's better to come back to GPU_USAGE_STATIC (which is the case here) AND normally (it's not the case here) to glBufferSubData to update the vbos)
- The "optimized" code works only when playing an animation DURING bge runtime (not in viewport playing timeline)
- On my computer, when playing animation in the test file (during bge runtime), i've 60fps in this branch, 45fps in master

Futher observations:

- It has been tested only with my hardware
- On linux, i've always better performances than on windows for deform tasks but i observed a slight performance gain in my test file (EDIT: Tested again with last code and worse performances in all cases using this)
... to complete

Test file:

https://ufile.io/elr7ywut
(W key at bge runtime to play anim)
(space bar to play turntable)

### CODE REVIEW

**Comment by lordloki** [comment]
In windows: 
- I confirm for your file (47fps in master and 61fps with this branch)
- With file (
[mixamo_setup_textured_faster_normal.zip](https://github.com/UPBGE/upbge/files/10369290/mixamo_setup_textured_faster_normal.zip)
) I have 12.5fps in master and 13.5fps with this branch.

I will update this comment with testing in other systems.

**Comment by youle31** [comment]
Thanks for tests!

**Comment by youle31** [comment]
I found something which seems more promising here: https://github.com/UPBGE/upbge/commit/fe02728256dd3bff48732f6903c02c58dd73d206 :)

**Comment by youle31** [comment]
I close this for now as we commited the other branch

**Pull request closed without merging**
