### PR TITLE
Expose bump height in the Parallax node

### PR DESCRIPTION
**Pull request by Feral3d**
Currently the Parallax vector mapping node has 2 available inputs:

1) The number of steps to the parallax effect
2) The Depth of the parallax effect

image

I am requesting that the height input be exposed to the parallax shader node, highlighted in this example image:

image

Here is a visual reference of how height offset works:
image
image
image
image

This is the standard behavior for height offset of a parallax shader-- options may be different in the version that is currently available.
If this is a simple code change, I would be immensely grateful for it's inclusion. I cannot express enough how useful this would be for users of the game engine as well as my personal project "The Shadows Lengthen". 

Best,
Thomas Murphy

### CODE REVIEW

**Comment by BluePrintRandom** [comment]
@Feral3d you may want to target this to 0.2.5 branch* this is trying to overwrite master

**Comment by Feral3d** [comment]
@BluePrintRandom  how do I make this change the targeted program? It seems I can't edit the "master" button.

**Comment by BluePrintRandom** [comment]
@youle31 how does he fix this commit?

will he have to close / open a new pull?

**Comment by Feral3d** [comment]
@BluePrintRandom  I think I changed it now-- is this correct?

**Comment by lordloki** [comment]
Where is the code that you are trying to merge?

Really, you are trying to merge upbge0.2.5 branch in master (It is not possible).

**Comment by Feral3d** [comment]
@lordloki This was my mistake. I am attempting to request at change to UPBGE version 2.5.0? Does this mean I should close this and post it targeting 2.5.0?

**Comment by lordloki** [comment]
Ah, you are proposing a feature request.
The pull request is only a tool to propose merge a code change that you did (in your upbge source clone) with upbge source code.
I will close this pull request and open an issue with the feature request then.

**Comment by BluePrintRandom** [comment]
I think he is saying he already made it?

**Comment by lordloki** [comment]
Maybe, I'm confused. :-)

**Comment by Feral3d** [comment]
I am sorry it's a two-part thing :I was hoping to request this as a feature and possibly help move if forward by attempting to make the change myself. I need this feature very much in my current game project).
Do you know if this would be a large change that would be difficult or is it a more straightforward and attainable change that someone of my coding skill level could achieve?

**Pull request closed without merging**
