### PR TITLE
UPBGE: Add an option to render several times per frame

### PR DESCRIPTION
**Pull request by youle31**
For the ones who prefer quality over performance.

### CODE REVIEW

**Review by mysticfall — APPROVED** [review]
It works perfectly on my end. Thanks for the great work!

**Comment by lordloki** [comment]
Wow!!! I checked and it worked fantastic. I tryed with 3 samples for frame and it was enough to have a incredible antialiasing.
For me it is OK. The code seems me OK too. Great great work!!

**Review by lordloki — APPROVED** [review]

**Comment by lordloki** [comment]
image

**Comment by BluePrintRandom** [comment]
I wonder - could we somehow take 8 samples at one time into a big buffer
and combine them as a last step?

similar to the gsoc about accelerating VR
https://docs.google.com/document/d/1zaSudNfSNLhwmNr19aIFJv8cnQf8GSupaIwZAF80_kA/edit

**Comment by youle31** [comment]
Thanks very much for review and tests! I merge this

**Pull request merged**
