### PR TITLE
UPBGE: Remove get/set text attribute from KX_FontObject

### PR DESCRIPTION
**Pull request by lordloki**

### CODE REVIEW

**Comment by youle31** [comment]
I think the modifications in KX_Font.cpp file have not been taken into account in the pull request. Else I agree to remove get/set.

We can leave an empty python type with no attributes and no methods

**Comment by youle31** [comment]
Alright : ). I tested last time and it was ok then I approve.

**Review by youle31 — APPROVED** [review]

**Comment by youle31** [comment]
I forgot: The bge.types.KX_Font.rst can be edited too

**Comment by lordloki** [comment]
Ah, sorry :-). I was doing modification directly using github editor and I can only commit one file at time.
Now, is all modified.

**Comment by youle31** [comment]
hehe yeah ok sorry, i reviewed to early : ) But all seems ok, and it's great for the new code snippet in the rst file!

**Pull request merged**
