### PR TITLE
UPBGE: Test converting instance collections at runtime

### PR DESCRIPTION
**Pull request by youle31**
It's to try to anwer this limitation: https://github.com/UPBGE/upbge/issues/1716

There are example files in the issue.

I'm a bit reluctant to do such things because it's complex and idk what bugs it can generate, but we can try anyway to include it in master to experiment I guess.

For now I only tested with the files included in the issue report, and I did not debug anything, I didn't even print scene.objects after conversion to see if something was wrong.

For now, I just put it in PR list if someone wants to test/review it, but there is no ermergency and if someone think it can lead to issues, we can abandon it.

I see 1 case where it could be problematic: When we add an instance collection with Full Duplication option checked (not tested).

EDIT:

- Tested in debug build and no problem noticed
- Tested with print(scene.objects) and no problem noticed
- Fixed issue with Full Duplication option in this commit: https://github.com/UPBGE/upbge/pull/1798/commits/6f49f09429595aa020e628659a1e9d2fb59cfd68
Test file for the Full Duplication bug before this commit:

[insta_col_spawn_duplica_rb_joint.zip](https://github.com/UPBGE/upbge/files/10810635/insta_col_spawn_duplica_rb_joint.zip)

EDIT2: The issue with full duplication option is that each time blenderdataconversion is done, it adds a new dupligroup/groupobj to object list and DupliGroupRecurse is called for ALL objects in objeclist/active gameobjects list.

I guess anyway blenderdataconversion was not meant to be called during runtime, then it was not really an issue.

For now, I think that this commit https://github.com/UPBGE/upbge/pull/1798/commits/6f49f09429595aa020e628659a1e9d2fb59cfd68 is enough but another way to fix this specific issue (if we have a new report one day), would just be to remove dupligroup objects from active gamobj list after DupligroupRecurse has been called (at the very end of blenderdataconversion)

SUB-EDIT: Finally, I tried to arrange this issue in these commits:
https://github.com/UPBGE/upbge/pull/1798/commits/282f292ba9bd8a390bd660b698c22489ae9186e0
https://github.com/UPBGE/upbge/pull/1798/commits/effc031ce4f1621448679c536576617b5297e614
https://github.com/UPBGE/upbge/pull/1798/commits/5764b048aab5c899104a8398429ce7477a888b75

but we can keep "safeguards" to avoid "Full Duplication" of an instance collection because idk in what case it could be useful.

EDIT3: Try adding instance collection several times after this commit https://github.com/UPBGE/upbge/pull/1798/commits/282f292ba9bd8a390bd660b698c22489ae9186e0

Test file for add insta col sevral times:
[insta_col_added_several_times.zip](https://github.com/UPBGE/upbge/files/10821088/insta_col_added_several_times.zip)

### CODE REVIEW

**Comment by lordloki** [comment]
Thanks for merging with master. I was having issues reverting to former máster to compile this pull (they were issues with addons folder location due last blender commits). I will test this night. Great work

**Comment by youle31** [comment]
yes, I had issues too. No pb, thanks in advance for your tests!

**Comment by lordloki** [comment]
I just test all the files, the ones added in the pull and the ones in the github issue, and they work perfectly.
The code seems ok to me. Great great work as always.

**Review by lordloki — APPROVED** [review]

**Comment by youle31** [comment]
Thanks!! I noticed a bit weird behaviours in some cases early this morning in some cases (instance collection is sometimes visibled whereas only the instances should be visibled), but it can be fixed with python or i'll change the code later after merge to always hide instances collections in active list (if INSTANCE_SPAWN).

**Pull request merged**
