### PR TITLE
UPBGE: Try to fix object transform at scene restart

### PR DESCRIPTION
**Pull request by youle31**
issue at scene restart here:
https://github.com/UPBGE/upbge/issues/1531

### CODE REVIEW

**Comment by lordloki** [comment]
Hi, youle. Sorry for the delay. I couldn't find the exact file.

The issue was with this file [parenting bug.zip](https://github.com/UPBGE/upbge/files/7025061/parenting.bug.zip). If you remove  the IgnorePArentTx the "vibration"come back.

The rest of my test files are working ok.

**Comment by youle31** [comment]
Hi! Thanks very much! I had not anymore this test file and totally forgot it. Thanks to have find it. I'll try to find a solution.

**Comment by lordloki** [comment]
I will upload all my parent related files to the UPBGE-Testfiles repo.

**Comment by lordloki** [comment]
I tested all my parent related blends and they worked well. Also, I tested the scene restart blend and worked fine.
Great job!!!

**Comment by youle31** [comment]
Ok, great! Thanks!

**Pull request merged**
