### PR TITLE
Fix parsing of KX_PythonComponent names (#1230)

### PR DESCRIPTION
**Pull request by mysticfall**
Again, I don't know much of C/C++, so please feel free to change whatever part that needs to be improved.

(stackoverflow.com is such a wonderful place where you can steal code snippets that you don't really understand to fix your issue :sweat_smile:)

### CODE REVIEW

**Comment by youle31** [comment]
It works for me, then I'm ok. Congrats!

parenthesis: We have a crash in debug builds at ge exit when we are using components. It is not related to this commit, neither the previous one, neither my commit to recover last python components C code.

**Comment by youle31** [comment]
@lordloki : To check how it works, you can download mysticfall example here: https://github.com/UPBGE/upbge/issues/1230 (namespace-issue.tar.gz) and add the component in files named submodule like that:

- register component
- mymodule.submodule.MyComponent

I wait for your approbation to merge, or if you want you can merge directly.

Another parenthesis: I invited @mysticfall  as collaborator with write access to contribute to our repository.

**Comment by mysticfall** [comment]
@youle31 Joined the team now. Thanks much for the invitation!

**Comment by mysticfall** [comment]
Thanks much for the review!

**Pull request merged**
