### PR TITLE
UPBGE: Add "use soft shadow" per light switch

### PR DESCRIPTION
**Pull request by lordloki**
Based in https://developer.blender.org/D4166 by Alexander Court

image

Blend example: [test_lights.zip](https://github.com/UPBGE/upbge/files/5746018/test_lights.zip)

### CODE REVIEW

**Comment by lordloki** [comment]
Maybe I have to put the checkbox at Contact Shadows level

**Comment by youle31** [comment]
I think all these settings should be per lights, but as it is not us who decide for render things, if it is just this patch, it's not invasive and doesn't cause too much potential issues for merges, but if we include cascade size and cube size per light, and if we do even more experiments on shadows, we should have our own shadows pipeline in separate files to avoid conflicts with blender code.

If it is just for this patch, i'm ok to merge as it is.

**Review by youle31 — APPROVED** [review]

**Comment by youle31** [comment]
also, should the global setting in render tab modify the scene lights options?

**Comment by lordloki** [comment]
Yeah, i see it strange too but i think they focused all the related "render" setting in a closer place to improve the workflow. 

Well, i commit this that has little source impact. After, if we change more things we will see how to create our own pipeline if necessary.

**Comment by lordloki** [comment]
Arg, i forgot in the commit log. Thanks for the review youle.

**Comment by youle31** [comment]
No problem, Thanks to you! "Soft shadow override" makes it more clear too 👍

**Pull request merged**
