### PR TITLE
Suppress KX_GameObject::Update when it's suspended

### PR DESCRIPTION
**Pull request by mysticfall**
As discussed with youle on Discord.

### CODE REVIEW

**Comment by youle31** [comment]
Sorry, I was not concentrated on discord, I didn't understand...

About IsActionsSuspended it concerns only actions manager (playAction)

When you suspend logic it should stop both logic bricks and actions currently.

But an API could be implemented later to suspend only actions.

I think instead of IsActionsSuspended, SCA_IObject::m_suspended should be used.

**Comment by mysticfall** [comment]
Sorry, looks like _I_ wasn't concentrated either :) Anyway, changed it as requested. Thanks!

**Comment by youle31** [comment]
Thanks! It's ok for me. Later i'll do few modifs in the global naming/system to see more clear about  LogicAndAction or OnlyAction suspended.

**Review by youle31 — APPROVED** [review]

**Comment by youle31** [comment]
I take the liberty to merge this. If some issues are noticed later we can fix later. Thanks very much @mysticfall  !

**Pull request merged**
