### PR TITLE
UPBGE: Restore old collision behaviour

### PR DESCRIPTION
**Pull request by lordloki**
We restore old m_erp2 value.
Thanks to @youle31 for investigating and pointing the solution. I checked the value for bullet 2.83.7 and older and it was 0.8. If you see that the behaviour is better with 1.0 with can change it to that value.

Additionally, we move back to float precision instead of double in Bullet library

Double precision is slower than float one because the float one can use SSE improvements. WE have around 5-15% better performance with float precision.

[stress_test.zip](https://github.com/UPBGE/upbge/files/5498100/stress_test.zip)

Double precision can be interesting in open world with more than 10Km from center.

### CODE REVIEW

**Comment by BluePrintRandom** [comment]
also double is probably good for stuff with very small parts / simulations

**Comment by lordloki** [comment]
I found this:
The ERP specifies what proportion of the joint error will be fixed during the next simulation step.
If ERP=0 then no correcting force is applied and the bodies will eventually drift apart as the simulation proceeds.
If ERP=1 then the simulation will attempt to fix all joint error during the next time step.
However, setting ERP=1 is not recommended, as the joint error will not be completely fixed due to various internal approximations.
A value of ERP=0.1 to 0.8 is recommended (0.2 is the default).

I'm going to expose ERP and CFM values through bullet scene settings and python functions. I will update this pull request

**Comment by lordloki** [comment]
Capsule height fixed for new bullet version
image

**Comment by youle31** [comment]
I approve all the changes, if you want to merge. Unless you have other things to add in this pull request. Thanks for your work!

**Comment by youle31** [comment]
+10000000

**Pull request merged**
