### PR TITLE
Python proxy enhancements

### PR DESCRIPTION
**Pull request by mysticfall**
This PR contains an assortment of minor bug fixes and enhancements related to custom game object and Python components.

### CODE REVIEW

**Review by youle31 — APPROVED** [review]

**Comment by youle31** [comment]
It sounds good to me. Great work! As explained by Mysticfall on discord the pascal case regex splits the component name displayed in the UI:

Capturer

ThirdPerson becomes Third Person

💯

**Review by lordloki — APPROVED** [review]
It seems ok to me. Good work!!

**Comment by mysticfall** [comment]
Thanks for the test & review, both of you! :)

**Comment by mysticfall** [comment]
I will merge the PR after resolving the conflict. I suppose it's time for me to test out which VS Code extension is best to merge conflicts.

**Pull request merged**
