### PR TITLE
Update workflow action for UPBGE 0.3 / Python 3.10

### PR DESCRIPTION
**Pull request by mysticfall**
Update workflow action for UPBGE 0.3 / Python 3.10.

### CODE REVIEW

**Comment by youle31** [comment]
idk if it matters but i saw this: s/#APP_VERSION#/0.3.1

We choosed to use 0.31.0 version internally because we thought that using 0.3.1 would cause versioning (versioning_upbge.c) issues.

**Comment by mysticfall** [comment]
I think it'd be ok since it's only for determining the version of the Python module. The reason I decided it that way was because I wasn't sure if PyPI or any of Python's dependency management tools would properly recognise `0.4` as newer than `0.31` for instance.

**Review by lordloki — APPROVED** [review]
Changes seems ok to me. Good work!!

**Comment by mysticfall** [comment]
Thanks! I'll merge and close this now :)

**Pull request merged**
